# See https://github.com/travis-ci/travis-ci/issues/5899 for Travis-CI Chrome install
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

language: node_js
node_js:
        - '5'
before_install:
        - npm install -g grunt-cli
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
install:
        - npm install
        - grunt
